sonar.projectKey=LUSKTECH_gl1tch.xyz
sonar.organization=lusktech

sonar.projectName=gl1tch.xyz
sonar.projectVersion=1.0.0

sonar.sources=site/src,site/netlify
sonar.tests=site/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=site/coverage/lcov.info
sonar.typescript.lcov.reportPaths=site/coverage/lcov.info

sonar.exclusions=site/node_modules/**,site/dist/**,site/.astro/**,site/coverage/**,site/public/**,**/*.config.*

sonar.sourceEncoding=UTF-8
