name: ✨ Feature Request
description: Suggest an enhancement to gl1tch.xyz
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      placeholder: I'd like to … because …
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context / mockups
    validations:
      required: false
